# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on PR
on:
  push:
    branches: [ main ]
jobs:
  build_and_preview:
    if: '${{ github.event.push.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAPAPI_296515 }}'
          projectId: mapapi-296515
      - name: gcr.io/mapapi-296515/firebase
      args: ['deploy', '--project=mapapi-296515', '--only=hosting']
